languageCode = "en-us"
title = "sawada_ta"
theme = "sandy"
baseurl = "https://takusawa.github.io/"
canonifyurls = true
hasCJKLanguage = true
paginate = 10
googleAnalytics = "UA-90363459-1"

[params]
  description = "Hello! This is my blog site"
  author = "Takuya Sawada"

[taxonomies]
category = "categories"
tag = "tags"
